// src/pages/profile/Profile.svelte
<script lang="ts">
  import Box from 'components/bulma/Box.svelte'
  import Column from 'components/bulma/Column.svelte'
  import Columns from 'components/bulma/Columns.svelte'
  import Container from 'components/bulma/Container.svelte'
  import Section from 'components/bulma/Section.svelte'
  import Remote from 'components/remote/Remote.svelte'
  import UserDetailColumn from './UserDetailColumn.svelte'
  import UserActions from './UserActions.svelte'
  import Attendance from './Attendance.svelte'
  import Semesters from './Semesters.svelte'
  import Details from './Details.svelte'
  import Money from './Money.svelte'

  import {
    profileAttendance,
    profileDetails,
    profileMoney,
    profileSemesters,
    routeProfile,
  } from 'route/constructors'
  import { ProfileTab } from 'route/types'
  import { eagerQuery } from 'state/query'
  import { siteContext } from 'store/context'
  import { renderRoute } from 'route/render'

  export let email: string
  export let tab: ProfileTab | null

  $: [member, reloadMember] = eagerQuery('FullMember', { email })

  const allProfileTabs = [
    profileDetails,
    profileMoney,
    profileAttendance,
    profileSemesters,
  ]
</script>

<Section>
  <Container>
    <Remote data={$member}>
      <Columns slot="loaded" let:data={member}>
        <Column narrow>
          <!-- Profile Picture -->
          <img
            width={250}
            height={250}
            src={member.member.picture || 'https://picsum.photos/250'}
            alt=""
          />
        </Column>
        <Column>
          <UserDetailColumn member={member.member} />
          <br />
          <UserActions member={member.member} />
        </Column>
      </Columns>
    </Remote>
  </Container>
</Section>

{#if $siteContext.user?.positions.length}
  <Section>
    <Container>
      <Box>
        <Remote data={$member}>
          <svelte:fragment slot="loaded" let:data={member}>
            <div class="tabs">
              <ul>
                {#each allProfileTabs as profileTab}
                  <li class:is-active={tab?.route === profileTab.route}>
                    <a
                      href={renderRoute(
                        routeProfile(member.member.email, profileTab)
                      )}
                    >
                      {profileTab.name}
                    </a>
                  </li>
                {/each}
              </ul>
            </div>

            {#if tab?.route === 'attendance'}
              <Attendance
                member={member.member}
                onUpdate={() => reloadMember({ email })}
              />
            {:else if tab?.route === 'semesters'}
              <Semesters email={member.member.email} />
            {:else if tab?.route === 'money'}
              <Money
                transactions={member.member.transactions}
                onUpdate={() => reloadMember({ email })}
              />
            {:else if tab?.route === 'details'}
              <Details
                member={member.member}
                onUpdate={() => reloadMember({ email })}
              />
            {/if}
          </svelte:fragment>
        </Remote>
      </Box>
    </Container>
  </Section>
{/if}

// src/pages/profile/Page.tsx
import React, { useContext, useState, useEffect, useCallback } from "react";
import {
  ProfileTab,
  routeRoster,
  routeLogin,
  routeEditProfile,
  profileDetails,
  profileMoney,
  profileAttendance,
  profileSemesters,
  routeProfile,
  renderRoute
} from "state/route";
import { GlubHubContext, useGlubRoute } from "utils/context";
import {
  RemoteData,
  loading,
  notSentYet,
  SubmissionState,
  loaded,
  resultToRemote,
  sending,
  resultToSubmissionState,
  failedToSend
} from "state/types";
import { Member } from "state/models";
import { get, NewToken, deleteRequest, chain } from "utils/request";
import {
  getToken,
  setOldToken,
  setToken,
  fullName,
  getOldToken
} from "utils/helpers";
import {
  EmailLink,
  PhoneLink,
  Section,
  Container,
  Column,
  Columns,
  Box
} from "components/Basics";
import { ButtonGroup, Button, LinkButton } from "components/Buttons";
import { switchUser, deleteUser } from "state/permissions";
import ErrorBox from "components/ErrorBox";
import DeleteModal from "components/DeleteModal";
import { Details } from "./Details";
import { Attendance } from "./Attendance";
import { Semesters } from "./Semesters";
import { Money } from "./Money";
import { RemoteContent, RequiresPermission } from "components/Complex";

interface ProfileProps {
  email: string;
  tab: ProfileTab | null;
}

export const Profile: React.FC<ProfileProps> = ({ email, tab }) => {
  const { user, members, updateMembers } = useContext(GlubHubContext);

  const [member, setMember] = useState<RemoteData<Member>>(loading);

  const updateMember = useCallback(
    (member: Member) => {
      setMember(loaded(member));
      updateMembers(members.map(m => (m.email === member.email ? member : m)));
    },
    [setMember, members, updateMembers]
  );

  useEffect(() => {
    const loadMember = async () => {
      const member = members.find(m => m.email === email);

      if (member) {
        setMember(loaded(member));
      } else {
        const result = await get<Member>(`/members/${email}`);
        setMember(resultToRemote(result));
      }
    };

    loadMember();
  }, [email, members, setMember]);

  return (
    <>
      <Section>
        <Container>
          <RemoteContent
            data={member}
            render={member => (
              <Columns>
                <Column narrow>
                  <ProfilePic member={member} />
                </Column>
                <Column>
                  <ProfileTextContent member={member} />
                  <br />
                  <UserActions member={member} />
                </Column>
              </Columns>
            )}
          />
        </Container>
      </Section>
      {!!user?.positions?.length && (
        <Section>
          <Container>
            <Box>
              <RemoteContent
                data={member}
                render={member => (
                  <>
                    <ProfileTabs member={member} tab={tab || profileDetails} />
                    <TabContent
                      member={member}
                      tab={tab || profileDetails}
                      updateMember={updateMember}
                    />
                  </>
                )}
              />
            </Box>
          </Container>
        </Section>
      )}
    </>
  );
};

const ProfileTextContent: React.FC<{ member: Member }> = ({ member }) => (
  <>
    <p>
      <h1 className="subtitle is-3" style={{ marginBottom: "initial" }}>
        {fullName(member)}
      </h1>
      <i>"{member.about || "no quote"}"</i>
    </p>
    <br />
    {member.positions?.length ? member.positions.join(", ") : "Member"}
    <br />
    <EmailLink email={member.email} />
    <br />
    <PhoneLink phone={member.phoneNumber} />
    <br />
    {member.section || "Homeless"}
    <br />
    {member.major || "No major"}
    {member.minor && `, minoring in ${member.minor}`}
  </>
);

const ProfilePic: React.FC<{ member: Member }> = ({ member }) => (
  <img
    width={250}
    height={250}
    src={member.picture || "https://picsum.photos/250"}
    alt=""
  />
);

const UserActions: React.FC<{ member: Member }> = ({ member }) => {
  const { goToRoute } = useGlubRoute();
  const { user, updateUser, members, updateMembers } = useContext(
    GlubHubContext
  );

  const [loginAsState, setLoginAsState] = useState(notSentYet);
  const [deleteState, setDeleteState] = useState<SubmissionState | null>(null);

  const logout = useCallback(() => {
    setToken(null);
    updateUser(null);

    goToRoute(routeLogin);
  }, [updateUser, goToRoute]);

  const logBackIn = useCallback(async () => {
    const oldToken = getOldToken();
    if (!oldToken) return;

    setLoginAsState(sending);
    const result = await chain(get("logout"), () => {
      setOldToken(null);
      setToken(oldToken);
      return get<Member | null>("user");
    });

    setLoginAsState(resultToSubmissionState(result));
    if (result.successful) {
      updateUser(result.data);
    }
  }, [setLoginAsState, updateUser]);

  const loginAsMember = useCallback(async () => {
    setLoginAsState(sending);

    const result = await chain(
      get<NewToken>(`members/${member.email}/login_as`),
      newToken => {
        const token = getToken();
        setOldToken(token);
        setToken(newToken.token);
        return get<Member | null>("user");
      }
    );

    setLoginAsState(resultToSubmissionState(result));
    if (result.successful) {
      updateUser(result.data);
    }
  }, [setLoginAsState, updateUser, member]);

  const deleteMember = useCallback(async () => {
    setDeleteState(sending);

    const result = await deleteRequest(`members/${member.email}?confirm=true`);
    setDeleteState(resultToSubmissionState(result));

    if (result.successful) {
      updateMembers(members.filter(m => m.email !== member.email));
      goToRoute(routeRoster);
    }
  }, [setDeleteState, member.email, updateMembers, members, goToRoute]);

  if (user?.email === member.email) {
    return (
      <ButtonGroup>
        {getOldToken() ? (
          <Button onClick={logBackIn}>Log back in as yourself</Button>
        ) : (
          <Button onClick={logout}>Log out</Button>
        )}
        <LinkButton route={routeEditProfile}>Edit your profile</LinkButton>
      </ButtonGroup>
    );
  } else {
    const firstName = member.preferredName || member.firstName;

    return (
      <ButtonGroup>
        <RequiresPermission permission={switchUser}>
          <Button onClick={loginAsMember}>Log in as {firstName}</Button>
        </RequiresPermission>
        <RequiresPermission permission={deleteUser}>
          <Button onClick={() => setDeleteState(notSentYet)}>
            Delete {firstName}
          </Button>
        </RequiresPermission>

        {failedToSend(loginAsState) && <ErrorBox error={loginAsState.error} />}
        {deleteState && (
          <DeleteMemberModal
            member={member}
            state={deleteState}
            cancel={() => setDeleteState(null)}
            confirm={deleteMember}
          />
        )}
      </ButtonGroup>
    );
  }
};

interface DeleteMemberModalProps {
  member: Member;
  state: SubmissionState;
  cancel: () => void;
  confirm: () => void;
}

const DeleteMemberModal: React.FC<DeleteMemberModalProps> = ({
  member,
  state,
  cancel,
  confirm
}) => (
  <DeleteModal
    title={`Delete ${fullName(member)}?`}
    state={state}
    confirm={confirm}
    cancel={cancel}
  >
    <>
      Are you sure you want to delete {fullName(member)}?
      <br />
      <i>Think of what Uncle Ben would say. No, not the rice one.</i>
    </>
  </DeleteModal>
);

interface ProfileTabsProps {
  member: Member;
  tab: ProfileTab;
}

const ProfileTabs: React.FC<ProfileTabsProps> = ({ member, tab }) => (
  <div className="tabs">
    <ul>
      {[profileDetails, profileMoney, profileAttendance, profileSemesters].map(
        profileTab => (
          <li
            className={tab.route === profileTab.route ? "is-active" : undefined}
          >
            <a href={renderRoute(routeProfile(member.email, profileTab))}>
              {profileTab.name}
            </a>
          </li>
        )
      )}
    </ul>
  </div>
);

interface TabContentProps {
  member: Member;
  tab: ProfileTab;
  updateMember: (member: Member) => void;
}

const TabContent: React.FC<TabContentProps> = ({
  member,
  tab,
  updateMember
}) => {
  switch (tab.route) {
    case "attendance":
      return <Attendance member={member} />;
    case "semesters":
      return <Semesters member={member} />;
    case "money":
      return <Money member={member} />;
    case "details":
      return <Details member={member} update={updateMember} />;
  }
};
