// src/pages/profile/Semesters.svelte
<script lang="ts">
  import Table from "components/bulma/Table.svelte";
  import Remote from "components/remote/Remote.svelte";

  import { query } from "state/query";
  import { roundToTwoDigits } from "utils/helpers";
  import { MemberSemestersDocument } from "gql-operations";

  export let email: string;

  $: semesters = query(MemberSemestersDocument, { email });
</script>

<Remote data={$semesters}>
  <Table slot="loaded" let:data={semesters}>
    <thead>
      <tr>
        <th>Semester</th>
        <th>Enrollment</th>
        <th>Section</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      {#each semesters.member.semesters as semester}
        <tr class="no-bottom-border">
          <td>{semester.semester}</td>
          <td>{semester.enrollment || "Inactive"}</td>
          <td>{semester.section || "Homeless"}</td>
          <td>{roundToTwoDigits(semester.grades.grade)}</td>
        </tr>
      {/each}
    </tbody>
  </Table>
</Remote>

// src/pages/profile/Semesters.tsx
import React, { useState, useEffect } from "react";
import { Member, ActiveSemester } from "state/models";
import { RemoteData, loading, resultToRemote, mapLoaded } from "state/types";
import { get } from "utils/request";
import { RemoteContent } from "components/Complex";
import { roundToTwoDigits } from "utils/helpers";
import { Table } from "components/Table";

export const Semesters: React.FC<{ member: Member }> = ({ member }) => {
  const [semesters, setSemesters] = useState<RemoteData<ActiveSemester[]>>(
    loading
  );

  useEffect(() => {
    const loadSemesters = async () => {
      const url = `members/${member.email}?details=true`;
      const result = await get<{ semesters: ActiveSemester[] }>(url);
      setSemesters(mapLoaded(resultToRemote(result), x => x.semesters));
    };

    loadSemesters();
  }, [member, setSemesters]);

  return (
    <RemoteContent
      data={semesters}
      render={semesters => (
        <Table>
          <thead>
            <tr>
              <th>Semester</th>
              <th>Enrollment</th>
              <th>Section</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            {semesters.map(semester => (
              <tr className="no-bottom-border">
                <td>{semester.semester}</td>
                <td>{semester.enrollment || "Inactive"}</td>
                <td>{semester.section || "Homeless"}</td>
                <td>{roundToTwoDigits(semester.grades.grade)}</td>
              </tr>
            ))}
          </tbody>
        </Table>
      )}
    />
  );
};
