// src/pages/home/AttendanceGraph.tsx
import React, { useRef, useEffect } from "react";
import { GlubEvent } from "state/models";
import * as d3 from "d3";
import { HoveredEvent } from "./Page";
import { eventIsOver } from "utils/helpers";
import { GOLD_COLOR } from "state/constants";

interface AttendanceGraphProps {
  events: GlubEvent[];
  hover: (event: HoveredEvent | null) => void;
}

export const AttendanceGraph: React.FC<AttendanceGraphProps> = ({
  events,
  hover
}) => {
  const d3Container = useRef<SVGGElement | null>(null);

  const margin = { top: 20, right: 20, bottom: 20, left: 30 };
  const width = 1350;
  const height = 400;
  const pastEvents = events.filter(eventIsOver);

  const x = d3.scaleTime().rangeRound([margin.left, width - margin.right]);
  const y = d3.scaleLinear().rangeRound([height - margin.bottom, margin.top]);
  x.domain(d3.extent(events, event => event.callTime) as [number, number]);
  y.domain([0, 100]);

  useEffect(() => {
    if (!d3Container.current || !pastEvents.length) return;

    const svg = d3.select(d3Container.current).html("");

    // create axes
    svg
      .append("g")
      .attr("transform", `translate(0, ${height - margin.bottom})`)
      .call(d3.axisBottom(x).ticks(3));
    svg
      .append("g")
      .attr("transform", `translate(${margin.left}, 0)`)
      .call(d3.axisLeft(y));

    // draw the line between event grades
    const valueline = d3
      .line<{ callTime: number; partialScore: number }>()
      .x(event => x(event.callTime))
      .y(event => y(Math.max(0, event.partialScore)))
      .curve(d3.curveMonotoneX); // http://bl.ocks.org/d3indepth/b6d4845973089bc1012dec1674d3aff8
    svg
      .append("path")
      .datum([
        {
          callTime: pastEvents[0].callTime,
          partialScore: 0
        },
        ...pastEvents.map(event => ({
          callTime: event.callTime,
          partialScore: event.change!.partialScore
        })),
        {
          callTime: pastEvents[pastEvents.length - 1].callTime,
          partialScore: 0
        }
      ])
      .attr("class", "line")
      .attr("d", valueline);
  }, [pastEvents, margin, x, y]);

  return (
    <svg width={width} height={height}>
      <g ref={d3Container} />

      <g>
        {pastEvents.map(event => (
          <circle
            cx={x(event.callTime)}
            cy={y(Math.max(event.change!.partialScore, 0))}
            r={4}
            strokeWidth={3}
            className="attendanceDot"
          />
        ))}
      </g>
      <g>
        {pastEvents.map(glubEvent => (
          <circle
            cx={x(glubEvent.callTime)}
            cy={y(Math.max(glubEvent.change!.partialScore, 0))}
            r={8}
            fillOpacity={0}
            onMouseOver={event =>
              hover({
                event: glubEvent,
                x: event.clientX,
                y: event.clientY
              })
            }
            onMouseOut={() => hover(null)}
          />
        ))}
      </g>

      <defs>
        <linearGradient id="attendanceGradient" gradientTransform="rotate(90)">
          <stop offset="0%" stopColor={GOLD_COLOR} stopOpacity={0.85} />
          <stop offset="100%" stopColor={GOLD_COLOR} stopOpacity={0} />
        </linearGradient>
      </defs>
    </svg>
  );
};

// src/pages/home/AttendanceGraph.svelte
<script lang="ts">
  import { siteContext } from "store/context";
  import { onMount } from "svelte";
  import { derived, get } from "svelte/store";
  import { GOLD_COLOR } from "utils/constants";
  import { eventIsOver } from "utils/helpers";
  import { HoveredEvent } from "state/types";
  import { extent } from "d3-array";
  import { select } from "d3-selection";
  import { axisLeft, axisBottom } from "d3-axis";
  import { line, curveMonotoneX } from "d3-shape";
  import { scaleTime, scaleLinear } from "d3-scale";

  export let hoverEvent: (hover: HoveredEvent | null) => void;

  let graphElement: SVGElement;

  const pastEvents = derived(siteContext,
    context => context.user?.grades.eventsWithChanges.filter(
      event => eventIsOver(event.event)) || []);

  const margin = { top: 20, right: 20, bottom: 20, left: 30 };
  const width = 1350;
  const height = 400;

  const x = scaleTime().rangeRound([margin.left, width - margin.right]);
  const y = scaleLinear().rangeRound([height - margin.bottom, margin.top]);

  onMount(() => {
    const events = get(pastEvents);
    if (!graphElement || !events.length) return;

    x.domain(extent(events,
      event => new Date(event.event.callTime)) as [Date, Date]);
    y.domain([0, 100]);

    const svg = select(graphElement).html("");

    // create axes
    svg
      .append("g")
      .attr("transform", `translate(0, ${height - margin.bottom})`)
      .call(axisBottom<Date>(x).ticks(3));
    svg
      .append("g")
      .attr("transform", `translate(${margin.left}, 0)`)
      .call(axisLeft(y));

    // draw the line between event grades
    const valueline = line<{ callTime: Date; partialScore: number }>()
      .x(event => x(new Date(event.callTime)))
      .y(event => y(Math.max(0, event.partialScore)))
      .curve(curveMonotoneX); // http://bl.ocks.org/d3indepth/b6d4845973089bc1012dec1674d3aff8
    svg
      .append("path")
      .datum([
        {
          callTime: new Date(events[0].event.callTime),
          partialScore: 0
        },
        ...events.map(event => ({
          callTime: new Date(event.event.callTime),
          partialScore: event.change!.partialScore
        })),
        {
          callTime: new Date(events[events.length - 1].event.callTime),
          partialScore: 0
        }
      ])
      .attr("class", "line")
      .attr("d", valueline);
  });
</script>

<svg {width} {height}>
  <g bind:this={graphElement} />

  <g>
    {#each $pastEvents as event}
      <circle
        cx={x(new Date(event.event.callTime))}
        cy={y(Math.max(event.change.partialScore, 0))}
        r={4}
        stroke-width={3}
        class="attendanceDot"
      />
    {/each}
  </g>

  <g>
    {#each $pastEvents as event}]
      <circle
        cx={x(new Date(event.event.callTime))}
        cy={y(Math.max(event.change.partialScore, 0))}
        r={8}
        fill-opacity={0}
        on:mouseover={mouseEvent =>
          hoverEvent({
            event,
            x: mouseEvent.clientX,
            y: mouseEvent.clientY
          })
        }
        on:focus={focusEvent =>
          hoverEvent({
            event,
            x: focusEvent.currentTarget.getBoundingClientRect().x,
            y: focusEvent.currentTarget.getBoundingClientRect().y,
          })  
        }
        on:mouseout={() => hoverEvent(null)}
        on:blur={() => hoverEvent(null)}
      />
    {/each}
  </g>

  <defs>
    <linearGradient id="attendanceGradient" gradientTransform="rotate(90)">
      <stop offset="0%" stop-color={GOLD_COLOR} stop-opacity={0.85} />
      <stop offset="100%" stop-color={GOLD_COLOR} stop-opacity={0} />
    </linearGradient>
  </defs>
</svg>
