// src/pages/profile/Attendance.tsx
import React, { useState, useCallback, useEffect } from "react";
import { Member, Grades, SimpleAttendance, GlubEvent } from "state/models";
import {
  RemoteData,
  loading,
  isLoaded,
  notSentYet,
  sending,
  mapLoaded,
  resultToRemote,
  resultToSubmissionState,
  loaded
} from "state/types";
import { get, post } from "utils/request";
import { RemoteContent, SubmissionStateBox } from "components/Complex";
import { routeEvents, renderRoute } from "state/route";
import { CheckboxInput, TextInput, numberType } from "components/Forms";
import { dateFormatter } from "utils/datetime";
import { Table } from "components/Table";

export const Attendance: React.FC<{ member: Member }> = ({ member }) => {
  const [grades, updateGrades] = useState<RemoteData<Grades>>(loading);
  const [state, setState] = useState(notSentYet);

  const loadAttendance = useCallback(async () => {
    const result = await get<{ grades: Grades }>(
      `members/${member.email}?grades=true`
    );
    updateGrades(mapLoaded(resultToRemote(result), member => member.grades));
  }, [updateGrades, member]);

  const updateAttendance = useCallback(
    async (eventId: number, attendance: SimpleAttendance) => {
      if (!isLoaded(grades)) return;

      updateGrades(
        loaded({
          ...grades.data,
          eventsWithChanges: grades.data.eventsWithChanges.map(event =>
            event.id === eventId ? { ...event, attendance } : event
          )
        })
      );
      setState(sending);

      const url = `events/${eventId}/attendance/${member.email}`;
      const result = await post(url, attendance);

      setState(resultToSubmissionState(result));
      if (result.successful) {
        loadAttendance();
      }
    },
    [grades, member.email, setState, loadAttendance]
  );

  useEffect(() => {
    loadAttendance();
  }, [loadAttendance]);

  return (
    <>
      <RemoteContent
        data={grades}
        render={grades => (
          <Table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Event</th>
                <th>Type</th>
                <th>Should Attend?</th>
                <th>Did Attend?</th>
                <th>Minutes Late</th>
                <th>Point Change</th>
                <th>Partial Score</th>
                <th>Rationale</th>
              </tr>
            </thead>
            <tbody>
              {grades.eventsWithChanges.map(event => (
                <AttendanceRow event={event} update={updateAttendance} />
              ))}
            </tbody>
          </Table>
        )}
      />
      <SubmissionStateBox state={state} />
    </>
  );
};

interface AttendanceRowProps {
  event: GlubEvent;
  update: (eventId: number, attendance: SimpleAttendance) => void;
}

const AttendanceRow: React.FC<AttendanceRowProps> = ({ event, update }) => {
  const attendance = event.attendance || {
    shouldAttend: false,
    didAttend: false,
    confirmed: false,
    minutesLate: 0
  };

  return (
    <tr className="no-bottom-border">
      <td>{dateFormatter(event.callTime)}</td>
      <td>
        <a href={renderRoute(routeEvents(event.id, null))}>{event.name}</a>
      </td>
      <td>{event.type}</td>
      <td>
        <CheckboxInput
          content=""
          checked={attendance.shouldAttend}
          onChange={shouldAttend =>
            update(event.id, { ...attendance, shouldAttend })
          }
        />
      </td>
      <td>
        <CheckboxInput
          content=""
          checked={attendance.didAttend}
          onChange={didAttend => update(event.id, { ...attendance, didAttend })}
        />
      </td>
      <td>
        <TextInput
          type={numberType}
          value={attendance.minutesLate}
          onInput={minutesLate =>
            update(event.id, { ...attendance, minutesLate: minutesLate || 0 })
          }
          placeholder="0"
        />
      </td>
      <td>{event.change?.change}</td>
      <td>{event.change?.partialScore}</td>
      <td>{event.change?.reason}</td>
    </tr>
  );
};

// src/pages/events/Attendance.svelte
<script lang="ts">
  import StateBox from 'src/components/remote/StateBox.svelte'
  import CheckboxInput from 'src/components/forms/CheckboxInput.svelte'
  import TextInput from 'src/components/forms/TextInput.svelte'
  import Table from 'src/components/bulma/Table.svelte'

  import { AttendanceUpdate, FullEventQuery } from 'src/gql-operations'
  import { numberType } from 'src/state/input'
  import { query } from 'src/state/query'
  import {
    emptyLoaded,
    loading,
    RemoteData,
    stateFromResult,
  } from 'src/state/types'
  import { SECTION_ORDER, NO_SECTION } from 'src/utils/constants'

  export let eventId: number
  export let attendees: FullEventQuery['event']['allAttendance']
  export let onUpdate: () => void

  let state: RemoteData = emptyLoaded

  async function updateAttendee(
    email: string,
    update: Partial<AttendanceUpdate>
  ) {
    state = loading

    const attendee = attendees.find((a) => a.member.email === email)!
    const attendance = {
      didAttend: attendee.didAttend,
      shouldAttend: attendee.shouldAttend,
      confirmed: attendee.confirmed,
      minutesLate: attendee.minutesLate,
      ...update,
    }
    const result = await query('UpdateAttendance', {
      eventId,
      member: email,
      update: attendance,
    })

    state = stateFromResult(result)
    if (result.type === 'loaded') {
      onUpdate()
    }
  }

  $: groupedAttendees = SECTION_ORDER.map((section) => ({
    section: section || NO_SECTION,
    attendees: attendees.filter((a) => a.member.semester?.section === section),
  })).filter((group) => group.attendees.length)
</script>

<div>
  <Table fullwidth scrollable>
    {#each groupedAttendees as group}
      <thead>
        <tr>
          <td>{group.section}</td>
          <td>Did Attend</td>
          <td>Should Attend</td>
          <td>Confirmed</td>
          <td>Minutes Late</td>
        </tr>
      </thead>
      <tbody>
        {#each group.attendees as attendee}
          <tr class="no-bottom-border">
            <td>{attendee.member.fullName}</td>
            <td>
              <CheckboxInput
                content=""
                checked={attendee.didAttend}
                onChange={(didAttend) =>
                  updateAttendee(attendee.member.email, { didAttend })}
              />
            </td>
            <td>
              <CheckboxInput
                content=""
                checked={attendee.shouldAttend}
                onChange={(shouldAttend) =>
                  updateAttendee(attendee.member.email, { shouldAttend })}
              />
            </td>
            <td>
              <CheckboxInput
                content=""
                checked={attendee.confirmed}
                onChange={(confirmed) =>
                  updateAttendee(attendee.member.email, { confirmed })}
              />
            </td>
            <td>
              <TextInput
                type={numberType}
                value={attendee.minutesLate}
                onInput={(minutesLate) =>
                  updateAttendee(attendee.member.email, {
                    minutesLate: minutesLate || 0,
                  })}
              />
            </td>
          </tr>
        {/each}
      </tbody>
    {/each}
  </Table>
  <StateBox {state} />
</div>
