// src/pages/events/RequestAbsence.tsx
import React, { useState, useCallback, useContext, FormEvent } from "react";
import ErrorBox from "components/ErrorBox";
import { post, success } from "utils/request";
import { GlubHubContext } from "utils/context";
import { TextareaInput } from "components/Forms";
import { Subtitle, Title } from "components/Basics";
import { GlubEvent, AbsenceRequest } from "state/models";
import { BackButton, ButtonGroup, SubmitButton } from "components/Buttons";
import {
  notSentYet,
  errorSending,
  sending,
  isSending,
  failedToSend
} from "state/types";

interface RequestAbsenceProps {
  event: GlubEvent;
  cancel: () => void;
  success: (request: AbsenceRequest) => void;
}

export const RequestAbsence: React.FC<RequestAbsenceProps> = props => {
  const { user } = useContext(GlubHubContext);

  const [reason, setReason] = useState("");
  const [state, setState] = useState(notSentYet);

  const submit = useCallback(async (event: FormEvent) => {
    event.preventDefault();
    setState(sending);

    const body = { reason };
    const url = `absence_requests/${props.event.id}`;
    const resp = await post(url, body);

    if (resp.successful) {
      const newRequest = {
        member: user?.email || "",
        event: props.event.id,
        time: new Date().getTime(),
        reason,
        state: "Pending"
      };
      success(newRequest);
    } else {
      setState(errorSending(resp.error));
    }
  }, [setState, reason, props, user]);

  return (
    <div>
      <BackButton content="back to event" click={props.cancel} />
      <Title centered>Absence Request</Title>
      <Subtitle centered>for {props.event.name}</Subtitle>
      <br />
      <form onSubmit={submit}>
        <TextareaInput
          value={reason}
          onInput={setReason}
          title="But y tho"
          placeholder="Excuses, excuses"
          required
        />
        <ButtonGroup alignment="is-right">
          <SubmitButton color="is-primary" loading={isSending(state)}>
            Beg for Mercy
          </SubmitButton>
        </ButtonGroup>
      </form>
      {failedToSend(state) && <ErrorBox error={state.error} />}
    </div>
  );
};

// src/pages/events/RequestAbsence.svelte
<script lang="ts">
  import Subtitle from 'components/bulma/Subtitle.svelte'
  import Title from 'components/bulma/Title.svelte'
  import BackButton from 'components/buttons/BackButton.svelte'
  import ButtonGroup from 'components/buttons/ButtonGroup.svelte'
  import SubmitButton from 'components/buttons/SubmitButton.svelte'
  import TextareaInput from 'components/forms/TextareaInput.svelte'
  import ErrorBox from 'components/remote/ErrorBox.svelte'

  import { query } from 'state/query'
  import { replaceRoute } from 'store/route'
  import { eventDetails, routeEvents } from 'route/constructors'
  import { FullEventQuery } from 'gql-operations'
  import {
    emptyLoaded,
    loading,
    RemoteData,
    stateFromResult,
  } from 'state/types'

  export let event: FullEventQuery['event']
  export let onUpdate: () => void

  let reason = ''
  let state: RemoteData = emptyLoaded

  function goBackToDetails() {
    replaceRoute(routeEvents(event.id, eventDetails))
  }

  async function submitAbsence() {
    state = loading
    const result = await query('RequestAbsence', { eventId: event.id, reason })

    state = stateFromResult(result)
    if (result.type === 'loaded') {
      onUpdate()
      goBackToDetails()
    }
  }
</script>

<div>
  <BackButton content="back to event" click={goBackToDetails} />
  <Title centered>Absence Request</Title>
  <Subtitle centered>for {event.name}</Subtitle>
  <br />
  <form on:submit|preventDefault={submitAbsence}>
    <TextareaInput
      value={reason}
      onInput={(newReason) => (reason = newReason)}
      title="But y tho"
      placeholder="Excuses, excuses"
      required
    />
    <ButtonGroup alignment="is-right">
      <SubmitButton color="is-primary" loading={state.type === 'loading'}>
        Beg for Mercy
      </SubmitButton>
    </ButtonGroup>
  </form>
  {#if state.type === 'error'}
    <ErrorBox error={state.error} />
  {/if}
</div>
