// src/pages/admin/DocumentLinks.svelte
<script lang="ts">
  import Box from 'components/bulma/Box.svelte'
  import Title from 'components/bulma/Title.svelte'
  import Button from 'components/buttons/Button.svelte'
  import DeleteButton from 'components/buttons/DeleteButton.svelte'
  import TextInput from 'components/forms/TextInput.svelte'
  import Remote from 'components/remote/Remote.svelte'
  import StateBox from 'components/remote/StateBox.svelte'

  import { DocumentLink } from 'gql-operations'
  import { stringType } from 'state/input'
  import { eagerQuery, query } from 'state/query'
  import {
    emptyLoaded,
    loading,
    RemoteData,
    stateFromResult,
  } from 'state/types'
  import { get } from 'svelte/store'

  let name = ''
  let url = ''
  let state: RemoteData = emptyLoaded

  const [allLinks, reloadAllLinks] = eagerQuery('AllDocumentLinks', {})

  async function updateLink(link: DocumentLink) {
    state = loading
    const result = await query('CreateDocumentLink', link)

    state = stateFromResult(result)
    if (result.type === 'loaded') {
      reloadAllLinks()
    }
  }

  async function deleteLink(index: number) {
    const links = get(allLinks)
    if (links.type !== 'loaded') return

    const link = links.data.links[index]
    if (!link) return

    state = loading
    const result = await query('DeleteDocumentLink', { name: link.name })

    state = stateFromResult(result)
    if (result.type === 'loaded') {
      reloadAllLinks()
    }
  }

  async function createLink() {
    const links = get(allLinks)
    if (links.type !== 'loaded' || !name || !url) return

    state = loading
    const result = await query('CreateDocumentLink', { name, url })

    state = stateFromResult(result)
    if (result.type === 'loaded') {
      name = ''
      url = ''
      reloadAllLinks()
    }
  }
</script>

<Title>Document Links</Title>
<Box>
  <Remote data={$allLinks}>
    <table class="link-table" slot="loaded" let:data={links}>
      {#each links.links as link, index}
        <tr>
          <td style:padding-right="10px">
            <span class="inline-middle">
              {link.name}
            </span>
          </td>
          <td>
            <TextInput
              type={stringType}
              value={url}
              onInput={(url) => updateLink({ ...link, url })}
              placeholder="URL"
            />
          </td>
          <td>
            <span class="inline-middle">
              <DeleteButton click={() => deleteLink(index)} />
            </span>
          </td>
        </tr>
      {/each}
      <tr>
        <td>
          <b>New</b>
        </td>
      </tr>

      <tr>
        <td>
          <TextInput
            type={stringType}
            value={name}
            onInput={(newName) => (name = newName)}
            placeholder="Name"
          />
        </td>
        <td>
          <TextInput
            type={stringType}
            value={url}
            onInput={(newUrl) => (url = newUrl)}
            placeholder="URL"
          />
        </td>
        <td>
          <Button click={createLink}>sí</Button>
        </td>
      </tr>
    </table>
  </Remote>
  <StateBox {state} />
</Box>

<style>
  .link-table {
    border-spacing: 5px;
    border-collapse: separate;
  }

  .inline-middle {
    display: inline-block;
    vertical-align: middle;
  }
</style>

// src/pages/admin/DocumentLinks.tsx
import React, { useState, useEffect, useCallback } from "react";
import {
  RemoteData,
  loading,
  notSentYet,
  resultToRemote,
  sending,
  loaded,
  resultToSubmissionState,
  isLoaded
} from "state/types";
import { DocumentLink, emptyDocumentLink } from "state/models";
import { get, post, deleteRequest } from "utils/request";
import { Title, Box } from "components/Basics";
import { TextInput, stringType } from "components/Forms";
import { Button, DeleteButton } from "components/Buttons";
import { RemoteContent, SubmissionStateBox } from "components/Complex";

export const DocumentLinks: React.FC = () => {
  const [links, updateLinks] = useState<RemoteData<DocumentLink[]>>(loading);
  const [newLink, updateNewLink] = useState<DocumentLink>(emptyDocumentLink);
  const [state, setState] = useState(notSentYet);

  const updateLink = useCallback(
    async (index: number, link: DocumentLink) => {
      if (!isLoaded(links)) return;

      setState(sending);
      const update = await post(`google_docs/${links.data[index].name}`, link);

      setState(resultToSubmissionState(update));
      if (update.successful) {
        updateLinks(loaded(links.data.map((l, i) => (i === index ? link : l))));
      }
    },
    [links, setState, updateLinks]
  );

  const deleteLink = useCallback(
    async (index: number) => {
      if (!isLoaded(links)) return;

      const link = links.data[index];
      if (!link) return;

      setState(sending);
      const result = await deleteRequest(`google_docs/${link.name}`);

      setState(resultToSubmissionState(result));
      if (result.successful) {
        updateLinks(loaded(links.data.filter((_, i) => i !== index)));
      }
    },
    [links, setState, updateLinks]
  );

  const createLink = useCallback(async () => {
    if (!isLoaded(links) || !newLink.name || !newLink.url) return;

    setState(sending);
    const result = await post(`google_docs`, newLink);

    setState(resultToSubmissionState(result));
    if (result.successful) {
      updateLinks(loaded([...links.data, newLink]));
      updateNewLink(emptyDocumentLink);
    }
  }, [links, newLink, setState, updateLinks, updateNewLink]);

  useEffect(() => {
    const loadLinks = async () => {
      const links = await get<DocumentLink[]>(`google_docs`);
      updateLinks(resultToRemote(links));
    };

    loadLinks();
  }, [updateLinks]);

  return (
    <>
      <Title>Document Links</Title>
      <Box>
        <RemoteContent
          data={links}
          render={links => (
            <table style={{ borderSpacing: "5px", borderCollapse: "separate" }}>
              {links.map((link, index) => (
                <tr key={link.name}>
                  <td style={{ paddingRight: "10px" }}>
                    <span
                      style={{
                        display: "inline-block",
                        verticalAlign: "middle"
                      }}
                    >
                      {link.name}
                    </span>
                  </td>
                  <td>
                    <TextInput
                      type={stringType}
                      value={link.url}
                      onInput={url => updateLink(index, { ...link, url })}
                      placeholder="URL"
                    />
                  </td>
                  <td>
                    <span
                      style={{
                        display: "inline-block",
                        verticalAlign: "middle"
                      }}
                    >
                      <DeleteButton click={() => deleteLink(index)} />
                    </span>
                  </td>
                </tr>
              ))}
              <tr>
                <td>
                  <b>New</b>
                </td>
              </tr>
              <NewLinkRow
                newLink={newLink}
                update={updateNewLink}
                create={createLink}
              />
            </table>
          )}
        />
        <SubmissionStateBox state={state} />
      </Box>
    </>
  );
};

interface NewLinkRowProps {
  newLink: DocumentLink;
  create: () => void;
  update: (link: DocumentLink) => void;
}

const NewLinkRow: React.FC<NewLinkRowProps> = ({ newLink, update, create }) => (
  <tr>
    <td>
      <TextInput
        type={stringType}
        value={newLink.name}
        onInput={name => update({ ...newLink, name })}
        placeholder="Name"
      />
    </td>
    <td>
      <TextInput
        type={stringType}
        value={newLink.url}
        onInput={url => update({ ...newLink, url })}
        placeholder="URL"
      />
    </td>
    <td>
      <Button onClick={create}>sí</Button>
    </td>
  </tr>
);
